server:
  port: 8000
eureka:
  client:
    service-url:
      defaultZone: http://localhost:${server.port}/eureka
    fetch-registry: false
    register-with-eureka: false
spring:
  application:
    name: registry-center