version: '3.7'
services:
  app:
    restart: always
    build: ./
    hostname: docker-spring-boot
    container_name: docker-spring-boot
    image: docker-spring-boot/latest
#    ports:
#      - 8080:8080
    volumes:
      - ./volumes/app:/app
  app-bak:
    restart: always
    build: ./
    hostname: docker-spring-boot
    container_name: docker-spring-boot
    image: docker-spring-boot/latest
    volumes:
      - ./volumes/app:/app
  nginx:
    depends_on:
      - app
    container_name: docker-nginx
    hostname: docker-nginx
    image: nginx:1.17.6
    environment:
      TZ: Asia/Shanghai
    restart: always
    expose:
      - 80
    ports:
      - 80:80
    links:
      - app
    volumes:
      - ./volumes/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./volumes/nginx/conf.d:/etc/nginx/conf.d
      - ./volumes/nginx/logs:/var/log/nginx
      - /var/run/docker.sock:/var/run/docker.sock